const types = {
    FETCH_STORY_START: 'FETCH_STORY_START',
    FETCH_STORY_ERROR: 'FETCH_STORY_ERROR',
    FETCH_STORY_RESULT: 'FETCH_STORY_RESULT',

    FETCH_COMMENTS_START: 'FETCH_COMMENTS_START',
    FETCH_COMMENTS_ERROR: 'FETCH_COMMENTS_ERROR',
    FETCH_COMMENTS_RESULT: 'FETCH_COMMENTS_RESULT',

    FETCH_STORY_AND_COMMENTS_START: 'FETCH_STORY_AND_COMMENTS_START',
    FETCH_STORY_AND_COMMENTS_ERROR: 'FETCH_STORY_AND_COMMENTS_ERROR',
    FETCH_STORY_AND_COMMENTS_RESULT: 'FETCH_STORY_AND_COMMENTS_RESULT',
}

export default types;