const types = {
    FETCH_STORIES: 'FETCH_STORIES',
    FETCH_STORIES_START: 'FETCH_STORIES_START',
    FETCH_STORIES_RESULT: 'FETCH_STORIES_RESULT',
    FETCH_STORIES_ERROR: 'FETCH_STORIES_ERROR',
}

export default types;