const types = {
    FETCH_STORIES_START: 'FETCH_STORIES_START',
    FETCH_STORIES_RESULT: 'FETCH_STORIES_RESULT',
    FETCH_STORIES_ERROR: 'FETCH_STORIES_ERROR',

    FETCH_STORY_START: 'FETCH_STORY_START',
    FETCH_STORY_RESULT: 'FETCH_STORY_RESULT',
    FETCH_STORY_ERROR: 'FETCH_STORY_ERROR',
}

export default types;